// req_C1TxRAM2PORT.v

// Generated using ACDS version 16.0 211

`timescale 1 ps / 1 ps
module req_C1TxRAM2PORT #(parameter DATA_WIDTH=580, ADDR_WIDTH=9)
	(
		input  wire [DATA_WIDTH-1:0] data,      //  ram_input.datain
		input  wire [ADDR_WIDTH-1:0]   wraddress, //           .wraddress
		input  wire [ADDR_WIDTH-1:0]   rdaddress, //           .rdaddress
		input  wire         wren,      //           .wren
		input  wire         clock,     //           .clock
		output wire [DATA_WIDTH-1:0] q          // ram_output.dataout
	);

	req_C1TxRAM2PORT_ram_2port_160_nfprwsy #(.DATA_WIDTH(DATA_WIDTH), .ADDR_WIDTH(ADDR_WIDTH)) 
	ram_2port_0 (
		.data      (data),      //  ram_input.datain
		.wraddress (wraddress), //           .wraddress
		.rdaddress (rdaddress), //           .rdaddress
		.wren      (wren),      //           .wren
		.clock     (clock),     //           .clock
		.q         (q)          // ram_output.dataout
	);

endmodule
