// fp_exp_arria10_nohard.v

// Generated using ACDS version 16.0 211

`timescale 1 ps / 1 ps
module fp_exp_arria10_nohard (
		input  wire [31:0] a,      //      a.a
		input  wire        areset, // areset.reset
		input  wire        clk,    //    clk.clk
		output wire [31:0] q       //      q.q
	);

	fp_exp_arria10_nohard_altera_fp_functions_160_724m2py fp_functions_0 (
		.clk    (clk),    //    clk.clk
		.areset (areset), // areset.reset
		.a      (a),      //      a.a
		.q      (q)       //      q.q
	);

endmodule
